export const CourseList = [
  { name: "UI/UX Design", path: "" },
  { name: "HTML & CSS", path: "" },
  { name: "Figma", path: "" },
  { name: "Graphic Design", path: "" },
  { name: "JavaScript", path: "" },
  { name: "Laravel", path: "" },
  { name: "Web Development", path: "" },
  { name: "PHP", path: "" },
  { name: "Flutter", path: "" },
  { name: "Data Analysis", path: "" },
  { name: "Python", path: "" },
  { name: "Android Development", path: "" },
  { name: "Kotlin", path: "" },
  { name: "iOS Development", path: "" },
  { name: "Java", path: "" },
  { name: "React Native", path: "" },
  { name: "Vue JS", path: "" },
  { name: "React JS", path: "" },
];
